<a href="https://colab.research.google.com/github/AnnJungChan/TECHLOSS_SIGNLAB/blob/main/WAIT/%EC%95%88%EC%A4%91%EC%B0%AC/2022-03-23/ECU_BIT_BY_SHIP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ECU의 CONTROL은 어떻게 산출되었는가?

- CONTROL은 비트신호로 알려져 있음

- 하지만, CONTROL에는 십진수 형태의 데이터로 구성되어 있음

- 십진수를 이진수로 변환하여 비트신호를 파악해본 결과, CONTROL이 의미하는 것을 판단할 수 없었음

- 8비트로 나타낼 수 있는 모든 2진법의 수를 나타낸 후, 이를 CONTROL과 대조하여 CONTROL의 의미를 파악할 것임

# 패키지 로딩

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
import numpy as np
import pandas as pd

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

# 데이터 로딩

In [2]:
ECU = pd.read_csv('/content/gdrive/MyDrive/DB/ECU.csv')

In [3]:
ECU.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620535 entries, 0 to 620534
Data columns (total 26 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   SHIP_ID          620535 non-null  object
 1   D_INDEX          620535 non-null  int64
 2   DEVICE_ID        620535 non-null  int64
 3   CONTROL          620535 non-null  int64
 4   V1               620535 non-null  float64
 5   V2               620535 non-null  float64
 6   V3               620535 non-null  float64
 7   V4               620535 non-null  float64
 8   V5               620535 non-null  float64
 9   V6               620535 non-null  float64
 10  V7               620535 non-null  float64
 11  V8               620535 non-null  float64
 12  C1               620535 non-null  int64
 13  C2               620535 non-null  int64
 14  C3               620535 non-null  int64
 15  C4               620535 non-null  int64
 16  C5               620535 non-null  int64
 17  C6               620535 non-null  int64
 18  C7               620535 non-null  int64
 19  C8               620535 non-null  int64
 20  TEMP             620535 non-null  float64
 21  CURRENT          620535 non-null  int64
 22  VOLTAGE          620535 non-null  float64
 23  CONTROL_CURRENT  620535 non-null  int64
 24  SYSTEM           620535 non-null  int64
 25  SECTION          620535 non-null  int64
dtypes: float64(10), int64(15), object(1)
memory usage: 123.1+ MB

In [4]:
SHIP_ID=ECU['SHIP_ID'].unique()
SHIP_ID

array(['T140113-00101', 'T140113-00102', 'T140113-00103', 'T140113-00104',
       'T140128-00703', 'T140703-00101', 'T140708-00101', 'T141027-00501',
       'T160127-00202', 'T170102-00101', 'T20180208001', 'T20180614001',
       'T20181218003', 'T20190115004', 'T20190324001', 'T20190527002',
       'T20191014001', 'T20191016008', 'T20200218004', 'T20200603001',
       'T20201209001', 'T20201210002', 'T20201210003', 'T20201210004',
       'T20201210005', 'T20201210006', 'T20201210008', 'T20210521011',
       'UnkownShip', 'T20191119009', 'T20181031003', 'T140110-00206',
       'T20201110002', 'T20180910004', 'T20200113001'], dtype=object)

In [5]:
for i in range(35):
  SHIP_ID[i]=ECU.loc[ECU['SHIP_ID'] == SHIP_ID[i],:]

11110000
11111100
11111111
00000000

# C1~C8과 CONTROL의 관계

In [6]:
SHIP_ID_BIT = []
SHIP_CONTROL = []
C = []
BIT_CONTROL = []
BIT = []
for i in range(35) :
  SHIP_CONTROL.append(pd.concat([SHIP_ID[i]['CONTROL'],SHIP_ID[i].iloc[:,12:20]],axis = 1))
  C.append(SHIP_CONTROL[i].iloc[:,1:])
  C[i] = C[i] != 0 
  C[i]=C[i].astype(int)
  C[i]=C[i]['C1'].astype(str) + C[i]['C2'].astype(str) + C[i]['C3'].astype(str) + C[i]['C4'].astype(str) + C[i]['C5'].astype(str) + C[i]['C6'].astype(str) + C[i]['C7'].astype(str) + C[i]['C8'].astype(str)
  BIT_CONTROL.append(pd.concat([SHIP_ID[i]['CONTROL'],C[i]],axis = 1))
  BIT.append(BIT_CONTROL[i].drop_duplicates())
  SHIP_ID_BIT.append(pd.DataFrame(BIT[i].sort_values(by = 'CONTROL')))

In [7]:
SHIP_ID_BIT[0]

   CONTROL         0
0       -1  00000000

In [8]:
SHIP_ID_BIT[1]

   CONTROL         0
1       -1  00000000

In [9]:
SHIP_ID_BIT[2]

        CONTROL         0
532523        0  00000000
428240       33  00000000
2            34  11111111
533518       34  11101111
533611       34  11100111
533645       34  11110111
568276       34  01111111
577015       34  00111111

In [10]:
SHIP_ID_BIT[3]

   CONTROL         0
3       34  11111111

In [11]:
SHIP_ID_BIT[4]

        CONTROL         0
4            -1  00000000
1385         -1  11100000
295147       -1  01100000
337743       -1  10100000

In [12]:
SHIP_ID_BIT[5]

   CONTROL         0
5        0  11100000

In [13]:
SHIP_ID_BIT[6]

      CONTROL         0
6          -1  00000000
6161       -1  11110000

In [14]:
SHIP_ID_BIT[7]

        CONTROL         0
429473       32  00000000
7            34  11111111
69361       160  00000000

In [15]:
SHIP_ID_BIT[8]

   CONTROL         0
8       -1  00000000

In [16]:
SHIP_ID_BIT[9]

   CONTROL         0
9       -1  00000000

In [17]:
SHIP_ID_BIT[10]

        CONTROL         0
104375       -1  00000000
10            0  11111111
560258        0  11111000
560245        0  10011000
458076        0  01000000
456948        0  10111101
383530        0  01001111
383477        0  00000110
358258        0  00000010
347755        0  11111011
256126        0  00001001
228382        0  11111110
206747        0  00001101
206742        0  00000001
100125        0  11111101
94135         0  10100000
84280         0  11011111
69184         0  00000000
49107         0  10111111
27060         0  01111111
579998        0  11011101
595737        0  11101111

In [18]:
SHIP_ID_BIT[11]

        CONTROL         0
4675         -1  00000000
11            0  11101111
51            0  11111111
98843         0  10111111
99993         0  00000000
269131        0  11011111
269401        0  11111110

In [19]:
SHIP_ID_BIT[12]

        CONTROL         0
12           -1  00000000
38           -1  11000000
136637       -1  11100000
367348       -1  10000000
367350       -1  01000000

In [20]:
SHIP_ID_BIT[13]

        CONTROL         0
13           -1  00000000
118          -1  11111111
572934       -1  01010101
614894       -1  01111111

In [21]:
SHIP_ID_BIT[14]

       CONTROL         0
14          -1  00000000
39          -1  11111111
35395       -1  01010011

In [22]:
SHIP_ID_BIT[15]

        CONTROL         0
15           34  11111111
269052       34  11110000
400332       40  00000000

In [23]:
SHIP_ID_BIT[16]

      CONTROL         0
16         -1  00000000
918        -1  11111111
1127       -1  10101010

In [24]:
SHIP_ID_BIT[17]

        CONTROL         0
17           -1  11000000
971          -1  00000000
19808        -1  11111111
565430       -1  11111100

In [25]:
SHIP_ID_BIT[18]

    CONTROL         0
18       34  10000000

In [26]:
SHIP_ID_BIT[19]

    CONTROL         0
19       34  11100000

In [27]:
SHIP_ID_BIT[20]

        CONTROL         0
21338        33  00000000
20           34  11111111
64678        34  00000000
162622       34  11100111
162637       34  11100101
166110       34  11010111
569307       34  11000111

In [28]:
SHIP_ID_BIT[21]

        CONTROL         0
21           -1  00000000
3198         -1  11111111
270605       -1  11110000

In [29]:
SHIP_ID_BIT[22]

        CONTROL         0
22            0  00000000
58           34  11111111
4105         34  00000000
269077       34  11110000

In [30]:
SHIP_ID_BIT[23]

        CONTROL         0
23           34  11111111
136628       34  11110000

In [31]:
SHIP_ID_BIT[24]

        CONTROL         0
24           -1  00000000
59           -1  11111111
1436         -1  11101011
137597       -1  10000010
138755       -1  11110111
163129       -1  11111110
269078       -1  11110000

In [32]:
SHIP_ID_BIT[25]

        CONTROL         0
25           -1  00000000
60           -1  11111111
269079       -1  11110000

In [33]:
SHIP_ID_BIT[26]

        CONTROL         0
26           -1  00000000
752          -1  11111111
76090        -1  11111011
76096        -1  11011011
82561        -1  10011011
208810       -1  11010110
336174       -1  11111001

In [34]:
SHIP_ID_BIT[27]

      CONTROL         0
27          0  00000000
32         34  11000000
881        34  00000000
1069       34  11111111
9230       34  01111111

In [35]:
SHIP_ID_BIT[28]

    CONTROL         0
28       34  11111111

In [36]:
SHIP_ID_BIT[29]

        CONTROL         0
97           -1  00000000
121          -1  11000000
6780         -1  11111111
14442        -1  10101010
19996        -1  01110111
43195        -1  11111011
276853       -1  11011111
305958       -1  11011110

In [37]:
SHIP_ID_BIT[30]

      CONTROL         0
336        -1  00000000
4710       -1  11100000

In [38]:
SHIP_ID_BIT[31]

     CONTROL         0
548       -1  00000000

In [39]:
SHIP_ID_BIT[32]

     CONTROL         0
586       34  11111111

In [40]:
SHIP_ID_BIT[33]

        CONTROL         0
1297         -1  00000000
1407         -1  11111011
1758         -1  11111111
22031        -1  10001000
40379        -1  01110111
83300        -1  11111101
84893        -1  01001100
105082       -1  10000000
137578       -1  01111111
360721       -1  00001111
399752       -1  11110111
521270       -1  00001100
553901       -1  00001000
562642       -1  10110111
613740       -1  11100000

In [41]:
SHIP_ID_BIT[34]

        CONTROL         0
76913         0  00000000
72794         1  00000000
25343        33  00000000
1788         34  11111111
432296       34  00000000
519366       34  11111110
619150       34  00001111
619196       34  11110111